### ISSUE TITLE
Number of clients in code

### ISSUE THREAD

**Issue by TomPostmus** [tabularelf/MultiClient#1]
Dear Tabularelf,

Is it possible to access the number of clients in code? The number of clients is set with the "Number_Of_Clients" option in the extension and it would also be useful to read it in code. For example, for automatically positioning the windows on screen depending on the number of clients. Thanks in advance for the response!

Kind regards,
Tom Postmus

**Comment by tabularelf** [comment]
You can use `MultiClientGetID()`, which will give you a number between 0-number of clients (-1 on release builds)
You can then use a switch/case and set the window position from there. Hopefully that helps!
